  mex('CXXFLAGS=\$CXXFLAGS -std=c++11 -Wall','-largeArrayDims',...
    'private/gasonMex.cpp','../common/gason.cpp',...
    '-I../common/','-outdir','private');

  mex('private/maskApiMex.c','../common/maskApi.c',...
    '-I../common/','-outdir','private');
